@Infrastructure_HostAddress = http://0.0.0.0:5260
@Infrastructure_HostWsAddress = ws://0.0.0.0:5260

### Create a new table
POST {{Infrastructure_HostAddress}}/api/table
Accept: application/json
Content-Type: application/json

{
    "game": "NoLimitHoldem",
    "maxSeat": 6,
    "smallBlind": 5,
    "bigBlind": 10,
    "chipCostAmount": 1,
    "chipCostCurrency": "Usd"
}
> {%
    client.global.set("tableUid", response.body.uid);
%}

### Connect Alice to events
WEBSOCKET {{Infrastructure_HostWsAddress}}/ws/table/{{tableUid}}/events/alice
> {%
    client.ws.onMessage = function(event) {
        console.log("Alice received event", event.data);
    }
%}

### Connect Bobby to events
WEBSOCKET {{Infrastructure_HostWsAddress}}/ws/table/{{tableUid}}/events/bobby
> {%
    client.ws.onMessage = function(event) {
        console.log("Bobby received event", event.data);
    }
%}

### Sit Alice down at the table
POST {{Infrastructure_HostAddress}}/api/table/{{tableUid}}/sit-down/alice
Accept: application/json
Content-Type: application/json

{
    "seat": 1,
    "stack": 1000
}

### Sit Bobby down at the table
POST {{Infrastructure_HostAddress}}/api/table/{{tableUid}}/sit-down/bobby
Accept: application/json
Content-Type: application/json

{
    "seat": 2,
    "stack": 900
}

### Submit Alice's action
POST {{Infrastructure_HostAddress}}/api/table/{{tableUid}}/submit-action/alice
Accept: application/json
Content-Type: application/json

{
  "type": "RaiseBy",
  "amount": 20
}

### Submit Bobby's action
POST {{Infrastructure_HostAddress}}/api/table/{{tableUid}}/submit-action/bobby
Accept: application/json
Content-Type: application/json

{
  "type": "CallBy",
  "amount": 15
}

### Stand Alice up from the table
POST {{Infrastructure_HostAddress}}/api/table/{{tableUid}}/stand-up/alice
Accept: application/json
Content-Type: application/json

{}

### Stand Bobby up from the table
POST {{Infrastructure_HostAddress}}/api/table/{{tableUid}}/stand-up/bobby
Accept: application/json
Content-Type: application/json

{}

### Get table detail
GET {{Infrastructure_HostAddress}}/api/table/{{tableUid}}
Accept: application/json

### Get table list
GET {{Infrastructure_HostAddress}}/api/table
Accept: application/json

###
